### ISSUE TITLE
Index exceeds the number of array elements

### ISSUE THREAD

**Issue by SaibotMagd** [liu-yikang/SHERM#3]
Using my own dataset an anisotroph MRI sigma_rat (T1 & T2):
![grafik](https://user-images.githubusercontent.com/67700096/108974678-fb133500-7685-11eb-9a8d-d0642e399b2c.png)

I get this error:
![grafik](https://user-images.githubusercontent.com/67700096/108974739-08302400-7686-11eb-8407-0916c5498347.png)

**Comment by SaibotMagd** [comment]
Update: I find out about 2 very important parameters I have to tune:
`brain_vol_range = [1500,1900]` in sherm.m
`get_convexity(mask, dx, dy, dz) > 0.85` (in sherm_parallel_2d.m for anisotropic images); I'm not pretty sure what there're doing but it just run if I change them.

I did some parameter tuning and for my data [1400, 2300] and >0.75 works best. Probably the Kernel size parameters could have an interesting effect. And the result seems to be effected by the size of the picture (larger = better). It would be nice to see some of your tuning reports.

**Comment by liu-yikang** [comment]
> Update: I find out about 2 very important parameters I have to tune:
> `brain_vol_range = [1500,1900]` in sherm.m
> `get_convexity(mask, dx, dy, dz) > 0.85` (in sherm_parallel_2d.m for anisotropic images); I'm not pretty sure what there're doing but it just run if I change them.
> 
> I did some parameter tuning and for my data [1400, 2300] and >0.75 works best. Probably the Kernel size parameters could have an interesting effect. And the result seems to be effected by the size of the picture (larger = better). It would be nice to see some of your tuning reports.

Thanks for reporting the issue and the solution. The first is the size of the brain in mm^2. The second is the convexity threshold of the target brain mask. They screen the brain mask candidates for the first round before comparing their shapes to the template's. So in your case, the initial conditions were too stringent to have any brain mask candidates left.

**Comment by jmlipman** [comment]
Hi. I had the same problem, but the parameters suggested did not work (led to the same error). Instead, I used [1400, 2500], and 0.55. Although this configuration did not produce any error, the segmentations were not good (see Figure below). Any idea what I could tune to make it work? My data is also anisotropic.

Another question, does Sherm look at the headers of the data? The headers of my images might be wrong, is that a problem for Sherm?

![Capture](https://user-images.githubusercontent.com/3540650/110104411-cbfc7200-7daf-11eb-9a23-4ae5de85e176.PNG)

Thanks!

**Comment by liu-yikang** [comment]
SHERM looks at your image header to figure out spatial resolution. I guess
that’s the problem.

**Comment by SaibotMagd** [comment]
> 
> Hi. I had the same problem, but the parameters suggested did not work (led to the same error). Instead, I used [1400, 2500], and 0.55. Although this configuration did not produce any error, the segmentations were not good (see Figure below). Any idea what I could tune to make it work? My data is also anisotropic.

I use a very easy (but time consuming) approach for the parameter tuning. 
1. set `brain_vol_range` (in sherm.m) pretty high (i use [1400, 2300] for my sigma rats, [300, 1000] for mice)
2. set the convexity treshold pretty low ( `if sum(mask(:)) < max_vol/(dx*dy*dz) && sum(mask(:)) > min_vol/(dx*dy*dz) && get_convexity(mask, dx, dy, dz) > 0.5` )
3. print the size-of-region-variable by ```

                convi = get_convexity(mask, dx, dy, dz);               
                fprintf("Convexity = %d \n", convi); 
``` 
(in the line before the convexity treshold in 2.) this only works if you deactivate the parallel loop 
(parfor -> for) so it will be very slow
4. check the output for the highest value, you should target to a value near or above 0.8
5. if the value in 4. is to low, increase the brain_vol_range, 
6. set the convexity treshold near the value you got from 4. (i.e. 0.8 -> convexity > 0.8)

My results are pretty great using this approach, even if I use the waxholm parameters 
for a sigma rat, and the allen mouse parameter for my mongolian gerbil.

PS: on my very slow pc (16GB Ram, 4cpu i7) i can only run files < 50MB but it last about 2 hours. So downsample 
the image to about 10-15MB then tune the parameter and upscale it afterwards to improve the result. The result should be 
better using larger images but the parameters stays the same and you can use the parfor-loop 
for the larger images (so comment the fprint command).
